
package org.datacontract.schemas._2004._07.cxs_subsystem;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoyaltyCardManagement.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LoyaltyCardManagement">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PrePrinted"/>
 *     &lt;enumeration value="AutoGenerated"/>
 *     &lt;enumeration value="UserDefined"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LoyaltyCardManagement", namespace = "http://schemas.datacontract.org/2004/07/CXS.SubSystem.Loyalty")
@XmlEnum
public enum LoyaltyCardManagement {

    @XmlEnumValue("PrePrinted")
    PRE_PRINTED("PrePrinted"),
    @XmlEnumValue("AutoGenerated")
    AUTO_GENERATED("AutoGenerated"),
    @XmlEnumValue("UserDefined")
    USER_DEFINED("UserDefined");
    private final String value;

    LoyaltyCardManagement(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LoyaltyCardManagement fromValue(String v) {
        for (LoyaltyCardManagement c: LoyaltyCardManagement.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
